version: '2'

services:
  janus-gateway:
    image: linagora/janus-gateway
    ports:
      - "80:80"
      - "7088:7088"
      - "8088:8088"
      - "8188:8188"
      - "8089:8089"
      - "10000-10200:10000-10200/udp"
    environment:
      - DOCKER_IP=${DOCKER_IP}
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
